version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # don't relate node_modules folder in container to host folder
      - .:/app
    depends_on: ["tests"]

  tests:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
    volumes:
      - /app/node_modules # don't relate node_modules folder in container to host folder
      - .:/app
    command: ["npm", "run", "test"] # override default container startup command